services:
  agent:
    build:
      context: agent/
      dockerfile: Dockerfile
    image: logview-agent:local

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: logview-app:local