services:
  agent:
    build:
      context: agent/
      dockerfile: Dockerfile
    image: logview-agent:local
    environment:
      - ACCESS_KEY=lv_HBPWoBRYy9ChaJ0zUOFArXoInFq2W4clzEDSqhTI
      - LOG_FILE=test.log
      - LOG_DIR=/log
      - PB_URL=http://app:8090
    ports:
      - "5678:5678"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: logview-app:local